//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaARSHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmacionCita
    {
        public int id_confirmacion { get; set; }
        public Nullable<int> id_paciente { get; set; }
        public Nullable<int> id_doctor { get; set; }
        public Nullable<int> id_hospital { get; set; }
        public Nullable<int> id_especialidad { get; set; }
        public Nullable<int> id_seguro { get; set; }
        public Nullable<int> id_horario { get; set; }
    
        public virtual Doctores Doctores { get; set; }
        public virtual Especialidades Especialidades { get; set; }
        public virtual Hospitales Hospitales { get; set; }
        public virtual Horarios Horarios { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        public virtual Seguros Seguros { get; set; }
    }
}
