//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaARSHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico_paciente
    {
        public int id_historico_paciente { get; set; }
        public Nullable<int> id_resultado_factura { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public Nullable<System.DateTime> fecha_cambio_estatus { get; set; }
    
        public virtual Estatus Estatus { get; set; }
        public virtual Resultado_factura Resultado_factura { get; set; }
    }
}
