//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaARSHospital
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsultasHospitalEntities9 : DbContext
    {
        public ConsultasHospitalEntities9()
            : base("name=ConsultasHospitalEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConfirmacionCita> ConfirmacionCita { get; set; }
        public virtual DbSet<Doctores> Doctores { get; set; }
        public virtual DbSet<Especialidades> Especialidades { get; set; }
        public virtual DbSet<Estatus> Estatus { get; set; }
        public virtual DbSet<Forma_de_pago> Forma_de_pago { get; set; }
        public virtual DbSet<Historico_paciente> Historico_paciente { get; set; }
        public virtual DbSet<Horarios> Horarios { get; set; }
        public virtual DbSet<Hospitales> Hospitales { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<Resultado_factura> Resultado_factura { get; set; }
        public virtual DbSet<Seguros> Seguros { get; set; }
    }
}
