//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaARSHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado_factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resultado_factura()
        {
            this.Historico_paciente = new HashSet<Historico_paciente>();
        }
    
        public int id_resultado_factura { get; set; }
        public Nullable<int> id_doctor { get; set; }
        public Nullable<int> id_forma_pago { get; set; }
        public Nullable<int> id_paciente { get; set; }
        public Nullable<int> id_seguro { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public Nullable<decimal> monto { get; set; }
    
        public virtual Doctores Doctores { get; set; }
        public virtual Forma_de_pago Forma_de_pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historico_paciente> Historico_paciente { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        public virtual Seguros Seguros { get; set; }
    }
}
